personajes_data = [
    {'name': 'Luke Skywalker', 'total_episodes': 6},
    {'name': 'Darth Vader', 'total_episodes': 6},
    {'name': 'Yoda', 'total_episodes': 6},
    {'name': 'Boba Fett', 'total_episodes': 5},
    {'name': 'C-3PO', 'total_episodes': 9},
    {'name': 'Leia', 'total_episodes': 7},
    {'name': 'Rey', 'total_episodes': 3},
    {'name': 'Kylo Ren', 'total_episodes': 3},
    {'name': 'Chewbacca', 'total_episodes': 8},
    {'name': 'Han Solo', 'total_episodes': 5},
    {'name': 'R2-D2', 'total_episodes': 9},
    {'name': 'BB-8', 'total_episodes': 3},
    {'name': 'Obi-Wan Kenobi', 'total_episodes': 7},
    {'name': 'Palpatine', 'total_episodes': 6},
]